package com.autobuses.vistas;

import com.autobuses.clases.Courtesy;
import com.autobuses.clases.Discount;
import com.autobuses.clases.utils.Funciones; 
import com.autobuses.enumeradores.EstadoBoleto;
import com.autobuses.enumeradores.LugarCompra;
import com.autobuses.enumeradores.Sexo;
import com.autobuses.negocio.CourtesyNegocio;
import com.autobuses.negocio.DiscountNegocio;
import com.autobuses.negocio.TicketNegocio;
import com.autobuses.negocio.TripNegocio;
import com.mysql.jdbc.StringUtils;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lahl_
 */
public class FrmBoleto extends javax.swing.JDialog {
    
    private int result = 0;
    private int idTrip = 0;    
    private double total = 0;
    private double total_original = 0;
    private double subtotal = 0;
    private double cambio = 0;
    private double descuento = 0;
    private double porcentaje = 0;
    private int asiento = 0;
    public int getResult(){
        return this.result;
    }
    /**
     * Creates new form FrmDetalleBoleto
     */
    public FrmBoleto(int asiento, int idTrip, String tipo_boleto) throws SQLException, ClassNotFoundException {
        initComponents();        
        this.idTrip = idTrip;
        //Se agregan radios al grupo de sexo
        grp_genero.add(rb_hombre);
        grp_genero.add(rb_mujer);
        //Se agragan radios al grupo de lugar de compra 
        grp_lugar_compra.add(rb_sucursal);
        grp_lugar_compra.add(rb_pueblo);
        //Se tipo de compra 
        grp_tipo_compra.add(rb_reservar);
        grp_tipo_compra.add(rb_comprar);
        this.asiento = asiento;
        lbl_titulo.setText("Boleto " + tipo_boleto + " #" + asiento);
        llenar_descuentos();
        obtener_precio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp_genero = new javax.swing.ButtonGroup();
        grp_lugar_compra = new javax.swing.ButtonGroup();
        grp_tipo_compra = new javax.swing.ButtonGroup();
        lbl_titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        rb_hombre = new javax.swing.JRadioButton();
        rb_mujer = new javax.swing.JRadioButton();
        rb_sucursal = new javax.swing.JRadioButton();
        rb_pueblo = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        txt_pagar = new javax.swing.JTextField();
        txt_subtotal = new javax.swing.JLabel();
        btn_pagar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        rb_comprar = new javax.swing.JRadioButton();
        rb_reservar = new javax.swing.JRadioButton();
        txt_cambio = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_total = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbo_descuento = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        btn_cortesia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("Detalle Del Boleto");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nombre:");
        jLabel1.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Telefono:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Genero:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Subtotal:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Total:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Lugar de Compra:");

        rb_hombre.setText("Hombre");

        rb_mujer.setText("Mujer");

        rb_sucursal.setSelected(true);
        rb_sucursal.setText("Sucursal");

        rb_pueblo.setText("Pueblo");

        txt_pagar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_pagar.setText("0.0");
        txt_pagar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pagarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_pagarKeyTyped(evt);
            }
        });

        txt_subtotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_subtotal.setText("0.0");

        btn_pagar.setText("Pagar");
        btn_pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pagarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Tipo de compra:");

        rb_comprar.setSelected(true);
        rb_comprar.setText("Comprar");

        rb_reservar.setText("Reservar");

        txt_cambio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_cambio.setText("0.0");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Pagar:");

        txt_total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_total.setText("0.0");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Cambio:");

        cbo_descuento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_descuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_descuentoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Descuento:");

        btn_cortesia.setText("Cortesía");
        btn_cortesia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cortesiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rb_hombre)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rb_mujer))
                                .addComponent(jLabel7)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rb_sucursal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rb_pueblo))
                                .addComponent(jLabel8))
                            .addGap(14, 14, 14))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(rb_comprar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rb_reservar)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_subtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_cambio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_pagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_cortesia)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_pagar)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbl_titulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_telefono, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbo_descuento, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbo_descuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_hombre)
                    .addComponent(rb_mujer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_sucursal)
                    .addComponent(rb_pueblo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_comprar)
                    .addComponent(rb_reservar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_subtotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_total)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_pagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_cambio))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pagar)
                    .addComponent(btn_cortesia))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pagarActionPerformed
        EstadoBoleto estado = rb_comprar.isSelected() ? EstadoBoleto.getOpcion(1) : EstadoBoleto.getOpcion(3);
        try {
            pagar_boleto(estado, "");
        } catch (SQLException ex) {
            Logger.getLogger(FrmBoleto.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado, por favor contacte a soporte técnico.", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_pagarActionPerformed
    private  boolean dot = false;
    private void txt_pagarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pagarKeyTyped
        char vChar = evt.getKeyChar();
        if (txt_pagar.getText().equals(""))
            dot = false;
        if (dot == false){
            if (vChar == '.') dot = true;
            else if (!(Character.isDigit(vChar)
                    || (vChar == KeyEvent.VK_BACK_SPACE)
                    || (vChar == KeyEvent.VK_DELETE))) {
                    evt.consume();
            }
        } else {
            if (!(Character.isDigit(vChar)
                    || (vChar == KeyEvent.VK_BACK_SPACE)
                    || (vChar == KeyEvent.VK_DELETE))) {
                    evt.consume();
            }
        }
    }//GEN-LAST:event_txt_pagarKeyTyped

    private void txt_pagarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pagarKeyReleased
        calcular_totales();
    }//GEN-LAST:event_txt_pagarKeyReleased

    private void btn_cortesiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cortesiaActionPerformed
        String cortesia = JOptionPane.showInputDialog("Por favor ingrese el código de cortesía");
        if (cortesia == null)
            cortesia = "";
        if (cortesia.trim().equals("")){
            JOptionPane.showMessageDialog(this, "No se introdujo ningún código de cortesía.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);            
        } else {
            try {
                if (CourtesyNegocio.validarCodigoCortesia(cortesia))
                    pagar_boleto(EstadoBoleto.CORTESIA, cortesia);
                else 
                    JOptionPane.showMessageDialog(this, "El código de cortesía no se encuentra activo o no es válido.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                Logger.getLogger(FrmBoleto.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FrmBoleto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btn_cortesiaActionPerformed

    private void cbo_descuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_descuentoActionPerformed
        int index = cbo_descuento.getSelectedIndex() - 1;
        if (index >= 0){
            this.porcentaje = descuentos.get(index).getPorcentaje();                        
        } else {
            this.porcentaje = 0;
        }
        calcular_totales();
    }//GEN-LAST:event_cbo_descuentoActionPerformed
    
    private DefaultComboBoxModel modelo = new DefaultComboBoxModel();
    private List<Discount> descuentos = new ArrayList<Discount>();
    private void llenar_descuentos() throws SQLException, ClassNotFoundException{
        modelo.removeAllElements();              
        modelo.addElement("Seleccionar"); 
        descuentos = DiscountNegocio.obtenerTodos();
        if (descuentos != null) {
            descuentos.forEach((viaje) -> {
                modelo.addElement(viaje.getName()); 
            });
        }
        cbo_descuento.setModel(modelo);
    }
    private void obtener_precio() throws SQLException, ClassNotFoundException{
        this.total = TripNegocio.obtenerPrecio(this.idTrip);
        this.total_original = total;
        txt_total.setText("" + this.total);        
        this.subtotal = Math.round((this.total * 100)/116);
        txt_subtotal.setText("" + this.subtotal);
    }
    private void calcular_totales(){
        double pagado = txt_pagar.getText().trim().equals("") ? 0 : Double.parseDouble(txt_pagar.getText().trim());
        
        this.descuento = (this.total_original * this.porcentaje)/100;
        this.total = this.total_original - this.descuento;           
        txt_total.setText(Math.round(total) + "");
        this.subtotal = Math.round((this.total * 100)/116);
        txt_subtotal.setText("" + this.subtotal);
        
        if (pagado > 0) {
            this.cambio = Math.round(pagado - this.total);
            if (this.cambio < 0){
                this.cambio = 0;
            }
            txt_cambio.setText("" + this.cambio);
        }
    }
    private void pagar_boleto(EstadoBoleto estado, String cortesia) throws SQLException{        
        //OBTENER LAS VARIABLES 
        int id_user = 1;
        String nombre = txt_nombre.getText().trim();
        String telefono = txt_telefono.getText().trim();
        //String cortesia = txt_cortesia.getText().trim();
        int id_descuento = 0;
        Sexo sexo = rb_hombre.isSelected() ? Sexo.getOpcion(1) : Sexo.getOpcion(2);
        LugarCompra lugar = rb_sucursal.isSelected() ? LugarCompra.getOpcion(1) : LugarCompra.getOpcion(2);        
        this.subtotal = txt_subtotal.getText().trim().equals("") ? 0 : Double.parseDouble(txt_subtotal.getText().trim());
        this.total = txt_total.getText().trim().equals("") ? 0 : Double.parseDouble(txt_total.getText().trim());
        double pagar = txt_pagar.getText().trim().equals("") ? 0 : Double.parseDouble(txt_pagar.getText().trim());
        this.cambio = txt_cambio.getText().trim().equals("") ? 0 : Double.parseDouble(txt_cambio.getText().trim());
        //VALIDAR CAMPOS OBLIGATORIOS
        if (cbo_descuento.getSelectedIndex() > 0){
            id_descuento = descuentos.get(cbo_descuento.getSelectedIndex() - 1).getId();            
        }        
        if (TicketNegocio.validarBoleto(this.idTrip, this.asiento)){
            JOptionPane.showMessageDialog(this, "El asiento de este viaje ya ha sido vendido.", "Pagar", JOptionPane.INFORMATION_MESSAGE);
            return;
        } else if (pagar < total && !rb_reservar.isSelected()){
            JOptionPane.showMessageDialog(this, "La cantidad a pagar debe ser mayor o igual al precio total.", "Pagar", JOptionPane.INFORMATION_MESSAGE);
            return;
        } else if (nombre.equals("")){
            JOptionPane.showMessageDialog(this, "El campo de nombre es obligatorio.", "Pagar", JOptionPane.INFORMATION_MESSAGE);
            return;
        } else if (telefono.equals("")){
            JOptionPane.showMessageDialog(this, "El campo de teléfono es obligatorio.", "Pagar", JOptionPane.INFORMATION_MESSAGE);
            return;
        } else if (!rb_hombre.isSelected() && !rb_mujer.isSelected()){
            JOptionPane.showMessageDialog(this, "El campo de genero es obligatorio.", "Pagar", JOptionPane.INFORMATION_MESSAGE);
            return;
        } else if (!rb_sucursal.isSelected() && !rb_pueblo.isSelected()){
            JOptionPane.showMessageDialog(this, "El campo lugar de compra es obligatorio.", "Pagar", JOptionPane.INFORMATION_MESSAGE);
            return;
        } else if (!rb_comprar.isSelected() && !rb_reservar.isSelected()){
            JOptionPane.showMessageDialog(this, "El campo de tipo de compra es obligatorio.", "Pagar", JOptionPane.INFORMATION_MESSAGE);
            return;
        }        
        Boolean res = TicketNegocio.pagar(idTrip, id_user, id_descuento, cortesia, nombre, telefono, sexo, subtotal, total, asiento, lugar, estado, total, cambio, total_original);//pedir negocio
        this.result = res ? 1 : 2;        
        if (res)
            this.dispose();
        else 
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado, por favor contacte a soporte técnico.", "Mensaje", JOptionPane.ERROR_MESSAGE);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cortesia;
    private javax.swing.JButton btn_pagar;
    private javax.swing.JComboBox<String> cbo_descuento;
    private javax.swing.ButtonGroup grp_genero;
    private javax.swing.ButtonGroup grp_lugar_compra;
    private javax.swing.ButtonGroup grp_tipo_compra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JRadioButton rb_comprar;
    private javax.swing.JRadioButton rb_hombre;
    private javax.swing.JRadioButton rb_mujer;
    private javax.swing.JRadioButton rb_pueblo;
    private javax.swing.JRadioButton rb_reservar;
    private javax.swing.JRadioButton rb_sucursal;
    private javax.swing.JLabel txt_cambio;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_pagar;
    private javax.swing.JLabel txt_subtotal;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JLabel txt_total;
    // End of variables declaration//GEN-END:variables
}
